# Cấu hình kết nối Supabase
# Vui lòng thay thế bằng URL và KEY thực tế của bạn từ Dashboard Supabase

SUPABASE_URL = "https://hctmqgplmgrsjdxcfwxe.supabase.co"
SUPABASE_KEY = "sb_publishable_fh7KjVT4KLrvYUEg7aIFoQ_K78G9tOE"
